import {chromium} from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
import http from 'http'; import fs from 'fs'; import path from 'path';
const root='/home/claude/prancharia';
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.pdf':'application/pdf'};
const srv=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/')p='/local.html';
  const f=path.join(root,p); if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('nf');}
  res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'}); fs.createReadStream(f).pipe(res);});
await new Promise(r=>srv.listen(8091,r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const pg=await b.newPage();
pg.on('pageerror',e=>console.log('PAGEERROR:',e.message,'\n',(e.stack||'').split('\n').slice(1,4).join('\n')));
pg.on('console',m=>{if(m.type()==='error')console.log('CONSOLE-ERR:',m.text().slice(0,300));});
await pg.goto('http://localhost:8091/local.html');
await pg.waitForSelector('[data-acao="criarEmp"]');
await pg.click('[data-acao="criarEmp"]'); await pg.waitForSelector('#modal .modal-caixa');
await pg.fill('#empNome','Teste Casa');
await pg.click('[data-tipo="casa"]'); await pg.waitForTimeout(150);
await pg.fill('#cmp_pavimentos','4');
await pg.click('[data-acao="salvarEmpNovo"]'); await pg.waitForTimeout(1500);
console.log('HASH:', await pg.evaluate('location.hash'));
console.log('CONTEUDO:', (await pg.$eval('#conteudo',e=>e.innerText)).slice(0,400));
await b.close(); srv.close(); process.exit(0);
