import {chromium} from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
import http from 'http'; import fs from 'fs'; import path from 'path';
const root='/home/claude/prancharia';
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.pdf':'application/pdf'};
const srv=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/')p='/local.html';
  const f=path.join(root,p); if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('nf');}
  res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'}); fs.createReadStream(f).pipe(res);});
await new Promise(r=>srv.listen(8097,r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const pg=await b.newPage({viewport:{width:1400,height:1000},deviceScaleFactor:1.4});
await pg.goto('http://localhost:8097/local.html');
await pg.waitForSelector('#nav button');
await pg.click('[data-rota="documentos"]');
await pg.setInputFiles('#entradaDocs',[root+'/testdata/EX01SUB_TER_E_SUPR00.pdf',root+'/testdata/EX05PISOSUB_E_TERR01.pdf']);
await pg.waitForFunction("document.querySelectorAll('table tbody tr').length>=2 && !document.querySelector('.progresso')",{timeout:240000});
await pg.click('[data-rota="painel"]'); await pg.waitForTimeout(600);
await pg.screenshot({path:root+'/s1.png'});
await pg.click('[data-rota="ambientes"]'); await pg.waitForSelector('#conteudo table');
const btn=await pg.$('button[data-acao="abrirAmbiente"]:has-text("ÁREA PETS")');
await btn.click(); await pg.waitForTimeout(1800);
await pg.screenshot({path:root+'/s2.png'});
const ev=await pg.$('button[data-acao="verEvidencia"]');
await ev.click(); await pg.waitForTimeout(2200);
await pg.screenshot({path:root+'/s3.png'});
await b.close(); srv.close(); process.exit(0);
