import {chromium} from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
import http from 'http'; import fs from 'fs'; import path from 'path';
const root='/home/claude/prancharia';
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.pdf':'application/pdf'};
const srv=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/')p='/local.html';
  const f=path.join(root,p); if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('nf');}
  res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'}); fs.createReadStream(f).pipe(res);});
await new Promise(r=>srv.listen(8093,r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const pg=await b.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1.4});
const err=[]; pg.on('pageerror',e=>err.push(e.message));
pg.on('console',m=>{if(m.type()==='error'&&!/fonts|TUNNEL|404/.test(m.text()))err.push(m.text().slice(0,200));});
await pg.goto('http://localhost:8093/local.html');
await pg.waitForSelector('#nav button');
await pg.click('[data-rota="documentos"]');
await pg.setInputFiles('#entradaDocs',[root+'/testdata/EX01SUB_TER_E_SUPR00.pdf',root+'/testdata/EX05PISOSUB_E_TERR01.pdf']);
await pg.waitForFunction("document.querySelectorAll('table tbody tr').length>=2 && !document.querySelector('.progresso')",{timeout:240000});
await pg.click('[data-rota="locais"]'); await pg.waitForTimeout(500);
await pg.fill('#buscaLocal','ÁREA PETS');
await pg.click('[data-acao="buscarLocal"]'); await pg.waitForTimeout(700);
console.log('LOCAIS:\n'+(await pg.$eval('#conteudo table',e=>e.innerText)));
await pg.screenshot({path:root+'/n1.png'});
await pg.click('[data-rota="painel"]'); await pg.waitForTimeout(600);
await pg.screenshot({path:root+'/n2.png'});
console.log('ERROS:',err.slice(0,5));
await b.close(); srv.close(); process.exit(0);
